# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d108a2f0e0e76e2e2946370ae572512a75b16faabbe82d7b474692a5470138f4c7715984ca1862a885a97473c22874c4af5378941680dbc86fbf6f3680b2183d

test:
  secret_key_base: 9059b88347427d20dd18cda54e7172f80fcc7b5311436dd21b248f2dee9d38e9b86b2b7eb86a1508716b920d3a22ca53892449ca15cdc7fe22bdd27d54015797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
